PROJECT_NAME = "OhMyCrypto"
DEFAULT_SYMBOL = "BTC/USDT"
DEFAULT_EXCHANGES = ["binance", "okx"]
DEFAULT_POLL_INTERVAL = 2.0
DEFAULT_MIN_SPREAD = 0.002
DEFAULT_TRADE_SIZE = 1000.0
DEFAULT_FEE_RATE = 0.001
DEFAULT_TIMEOUT = 10000