PROJECT_NAME = "OhMyCrypto"
DEFAULT_SYMBOL = "BTC/USDT"
DEFAULT_EXCHANGES = ["coinbase", "kraken"]
DEFAULT_POLL_INTERVAL = 2.0
DEFAULT_MIN_SPREAD = 0.002
DEFAULT_TRADE_SIZE = 1000.0
DEFAULT_MIN_PROFIT_USD = 2.0
DEFAULT_FEE_RATE = 0.001
DEFAULT_TIMEOUT = 10000
DEFAULT_ALERT_COOLDOWN_SEC = 30.0
DEFAULT_STALE_PRICE_MS = 60000
DEFAULT_ORDERBOOK_DEPTH_LIMIT = 20
DEFAULT_MAX_CONSECUTIVE_ERRORS = 3
DEFAULT_ALERT_PRICE_CHANGE_RATIO = 0.15

ALERT_SOUND_BY_SEVERITY = {
    "alert": "Glass",
    "escalated": "Ping",
}

ALERT_VOICE_BY_SEVERITY = {
    "alert": "Samantha",
    "escalated": "Good News",
}

ALERT_RATE_BY_SEVERITY = {
    "alert": 175,
    "escalated": 200,
}
